src/objects/Brackets_Match__c.object
<CustomObject>
    <fields>
        <fullName>Brackets_Round__c</fullName>
        <label>Round</label>
        <referenceTo>Brackets_Round__c</referenceTo>
        <relationshipLabel>Matches</relationshipLabel>
        <relationshipName>Matches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Conference__c</fullName>
        <inlineHelpText>If rounds are grouped in conferences, this is the conference the match is part of.</inlineHelpText>
        <label>Conference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Short description of the match</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FollowingBrackets_Match__c</fullName>
        <label>FollowingMatch</label>
        <referenceTo>Brackets_Match__c</referenceTo>
        <relationshipLabel>PreviousMatches</relationshipLabel>
        <relationshipName>PreviousMatches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FollowingIsHome__c</fullName>
        <defaultValue>true</defaultValue>
        <label>FollowingIsHome</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HomeBrackets_Team__c</fullName>
        <label>Team 1</label>
        <referenceTo>Brackets_Team__c</referenceTo>
        <relationshipLabel>HomeMatches</relationshipLabel>
        <relationshipName>HomeMatch</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HomeScore__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Score of Team 1 after the match end.</inlineHelpText>
        <label>Team 1 Score</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Keep the position respect to its round, each position should be unique.</description>
        <label>Position</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <inlineHelpText>Date of the match</inlineHelpText>
        <label>Schedule</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>VisitorBrackets_Team__c</fullName>
        <label>Team 2</label>
        <referenceTo>Brackets_Team__c</referenceTo>
        <relationshipLabel>VisitorMatches</relationshipLabel>
        <relationshipName>VisitorMatches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VisitorScore__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Score of Team 2 after the match end.</inlineHelpText>
        <label>Team 2 Score</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WinnerBrackets_Team__c</fullName>
        <inlineHelpText>Match winner (Team 1 or Team 2)</inlineHelpText>
        <label>Winner Team</label>
        <referenceTo>Brackets_Team__c</referenceTo>
        <relationshipLabel>WinnerMatches</relationshipLabel>
        <relationshipName>WinnerMatches</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Match</label>
    <nameField>
        <displayFormat>MA-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Brackets_Round__c.object
<CustomObject>
    <fields>
        <fullName>Brackets_Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Brackets_Tournament__c</referenceTo>
        <relationshipLabel>Rounds</relationshipLabel>
        <relationshipName>Rounds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>Last date to make predictions for the round.</inlineHelpText>
        <label>Deadline</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>End__c</fullName>
        <inlineHelpText>End date of the round, calculated with the date of the last match.</inlineHelpText>
        <label>End</label>
        <summarizedField>Brackets_Match__c.Schedule__c</summarizedField>
        <summaryForeignKey>Brackets_Match__c.Brackets_Round__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MinScheduleBrackets_Match__c</fullName>
        <label>MinScheduleMatch</label>
        <summarizedField>Brackets_Match__c.Schedule__c</summarizedField>
        <summaryForeignKey>Brackets_Match__c.Brackets_Round__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>RoundNumber__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Number indicating the position of the round, being 1 the first round</inlineHelpText>
        <label>Round Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ScorePoints__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Points a user wins for each correct prediction in the round</inlineHelpText>
        <label>Score Points</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <inlineHelpText>Start date of the round, calculated with the date of the first match.</inlineHelpText>
        <label>Start</label>
        <summarizedField>Brackets_Match__c.Schedule__c</summarizedField>
        <summaryForeignKey>Brackets_Match__c.Brackets_Round__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Round</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Brackets_Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Allow_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CronTrigger__c</fullName>
        <description>Save CronTrigger Referenced ID</description>
        <label>CronTrigger</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>Deadline for the &quot;Full tournament&quot; type pools.</inlineHelpText>
        <label>Deadline</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>General description of the tournament.</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>End__c</fullName>
        <inlineHelpText>Tournament end date, calculated with the date of the last match played</inlineHelpText>
        <label>End Date</label>
        <summarizedField>Brackets_Round__c.End__c</summarizedField>
        <summaryForeignKey>Brackets_Round__c.Brackets_Tournament__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaxRoundNumber__c</fullName>
        <label>MaxRoundNumber</label>
        <summarizedField>Brackets_Round__c.RoundNumber__c</summarizedField>
        <summaryForeignKey>Brackets_Round__c.Brackets_Tournament__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <inlineHelpText>Tournament start date, calculated with the date of the first match played</inlineHelpText>
        <label>Start Date</label>
        <summarizedField>Brackets_Round__c.Start__c</summarizedField>
        <summaryForeignKey>Brackets_Round__c.Brackets_Tournament__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TeamCount__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Number of teams that participate in the tournament</inlineHelpText>
        <label>Team Count</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Which type of tournament this is?

Types supported include: &quot;NFL Playoff&quot; with fixed 12 teams and &quot;Standard&quot; a single elimination type of tournament.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>NFL Playoff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Update_Source__c</fullName>
        <label>Update Source</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isChild__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enabled if a tournament is imported from a URL</description>
        <label>isChild</label>
        <type>Checkbox</type>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BracketsTriggerUtilities.cls
/*
Copyright (c) 2011, salesforce.com, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, 
    this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
    this list of conditions and the following disclaimer in the documentation 
    and/or other materials provided with the distribution.
    * Neither the name of the salesforce.com, Inc. nor the names of its contributors 
    may be used to endorse or promote products derived from this software 
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
OF THE POSSIBILITY OF SUCH DAMAGE.

*/

public with sharing class BracketsTriggerUtilities {
    
    //Brackets_Match__c
    public static List<Brackets_Match__c>            triggerMatchList            = new List<Brackets_Match__c>();
    public static Map<Id,Brackets_Match__c>          triggerMatchMap             = new Map<Id,Brackets_Match__c>();
    public static List<Id>                  triggerMatchIds             = new List<Id>();
    public static Map<Id,Brackets_Match__c>          triggerListObject           = new Map<Id,Brackets_Match__c> ();
     
    //Brackets_Round__c
    public static List<Brackets_Round__c>            triggerRoundList            = new List<Brackets_Round__c>();
    public static Map<Id,Brackets_Round__c>          triggerRoundMap             = new Map<Id,Brackets_Round__c>();
    public static List<Id>                  triggerRoundIds             = new List<Id>();
    public static Map<Id,Brackets_Round__c>          triggerRoundObject          = new Map<Id,Brackets_Round__c>();
    
    //Brackets_Tournament__c
    public static List<Brackets_Tournament__c>       triggerTournamentList       = new List<Brackets_Tournament__c>();
    public static Map<Id,Brackets_Tournament__c>     triggerTournamentMap        = new Map<Id,Brackets_Tournament__c>();
    public static List<Id>                  triggerTournamentIds        = new List<Id>();
    public static Map<Id,Brackets_Tournament__c>     triggerTournamentObject     = new Map<Id,Brackets_Tournament__c>();
    
    
    
    /**
    * Populate all list if are not yet.
    * @params matchList : Get the list of current Matchs
    */
    public static void newTriggerInstance( List<Brackets_Match__c> matchList ) {
        
        
        
        if( BracketsTriggerUtilities.triggerTournamentList.isEmpty() && !matchList.isEmpty() ) {
            
            List<Id> auxMatch = new List<Id>();
            String auxTourId; 
            for( Brackets_Match__c mi : matchList ) { auxMatch.add( mi.Id ); }
            for( Brackets_Match__c t : [Select Brackets_Round__r.Brackets_Tournament__c from Brackets_Match__c where Id IN : auxMatch] ){
                auxTourId = t.Brackets_Round__r.Brackets_Tournament__c;
                break;
            }

            
            
            for( Brackets_Tournament__c t : [    Select t.isChild__c, t.Version__c, t.Update_Source__c, t.Type__c, t.TeamCount__c, t.Start__c, t.Allow_Update__c, 
                                        t.Name, t.MaxRoundNumber__c, t.Id, t.ExternalId__c, t.End__c, t.Description__c, t.CronTrigger__c,
                                        (Select Id, Name, Deadline__c, ExternalId__c, RoundNumber__c, ScorePoints__c, End__c,
                                        MinScheduleBrackets_Match__c, Start__c, Brackets_Tournament__c From Rounds__r)
                                        from Brackets_Tournament__c t where t.Id =: auxTourId ] ) {
            //-------- Populate the Different List and Maps  -----------------//
            
                //Tournament
                BracketsTriggerUtilities.triggerTournamentList.add( t ) ;
                BracketsTriggerUtilities.triggerTournamentMap.put( t.Id , t );
                BracketsTriggerUtilities.triggerTournamentIds.add( t.Id );
                
                //Rounds
                for( Brackets_Round__c r : t.Rounds__r ) {
                    BracketsTriggerUtilities.triggerRoundList.add( r ) ;
                    BracketsTriggerUtilities.triggerRoundIds.add( r.Id );
                    BracketsTriggerUtilities.triggerRoundMap.put( r.Id, r );
                }
            }//EndFor
            
            //Populate Brackets_Match__c with all matches for this tournament
            for( Brackets_Match__c m : [ Select m.WinnerBrackets_Team__c, m.VisitorBrackets_Team__c, m.VisitorScore__c, m.Schedule__c, m.Brackets_Round__c, 
                                m.Position__c, m.Name, m.Id, m.HomeBrackets_Team__c, m.HomeScore__c, m.FollowingBrackets_Match__c, 
                                m.FollowingIsHome__c, m.ExternalId__c, m.Description__c, m.Conference__c From Brackets_Match__c m 
                                where m.Brackets_Round__c IN: BracketsTriggerUtilities.triggerRoundIds ] ){
            
            //-------- Populate Match List and Maps  -----------------//
                BracketsTriggerUtilities.triggerMatchList.add( m ) ;
                BracketsTriggerUtilities.triggerMatchIds.add( m.Id );
                BracketsTriggerUtilities.triggerMatchMap.put( m.Id, m );
                
            }
            
        }//EndIf
    }
    
}